name: Security Scan
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Download and Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.tar.gz
          tar -zxvf trivy_0.59.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: build image from dockerfile
        run: docker build -t dev-app-image:${{ github.sha }} .

      - name: scan docker image
        run: trivy image dev-app-image:${{ github.sha }}